--- #YAML:1.0
name:         Sub-Contract
abstract:     Pragmatic contract programming
version:      0.01
author:
    - Erwan Lemonnier <erwan@cpan.org>
license:      perl
distribution_type: module
requires:
    Hook::WrapSub:                 0.03
    Data::Dumper:                  2.10
build_requires:
    Test::More:                    0
    Test::Pod:                     0
    Test::Pod::Coverage:           0
ressources:
    license: http://dev.perl.org/licenses/
    homepage: http://sourceforge.net/projects/xirr4perl
    bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Finance-Math-IRR
    repository: https://sourceforge.net/cvs/?group_id=193420
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
